### ISSUE TITLE
duration format

### ISSUE THREAD

**Issue by pettarin** [HadrienGardeur/audiobook-manifest#6]
I see that the example has duration attributes with values like ``1H23M45S`` or ``12M``.

Is this format mandated by some parent specification (that I ignore)?

If not, I suggest using plain seconds, and leave "presentational sugar" (i.e. ``3672`` => ``1h 1m``) to the UA/RS. Or, at least, be consistent and adopt the (zoo) formats for clipBegin/clipEnd values in EPUB 3 Media Overlays.

**Comment by pettarin** [comment]
Also, here: https://github.com/readium/webpub-manifest#the-link-object it says:

> duration indicates the length of the linked resource in seconds

**Comment by HadrienGardeur** [comment]
Yes that's a very good point, just to give a bit of background:

- the schema.org element that we're using in the context definition is based on an ISO 8601 duration: http://schema.org/duration
- that said, my initial impulse was that seconds would be better/easier
- I've been a bit torn between these two, but now that we've worked on implementing audio/SMIL support in Readium-2, I strongly feel that using a float + seconds is the better option, since this gives us miliseconds precision and an easy format to work with

**Comment by pettarin** [comment]
This might prove to be an interesting read, then: https://github.com/IDPF/epub-revision/issues/579

**Comment by HadrienGardeur** [comment]
Yeah we've just had to parse SMIL clock values in Readium-2 and it was the most painful part of the implementation for media overlay.

**Comment by pettarin** [comment]
It is not painful (implementing some HPC code in assembly _is_ painful). It is just idiotic supporting formats no one ever uses. Whatever.

**Comment by HadrienGardeur** [comment]
Which is exactly why we dropped it for this specification and also for Readium-2, everything is now expressed in seconds.

**Comment by pettarin** [comment]
Good. So I guess you can close this issue --- or am I missing something?

**Comment by HadrienGardeur** [comment]
I think that we can close it now.
